export type GameTemplateEngine =
  | 'phaser'
  | 'web'
  | 'unity'
  | 'godot'
  | 'unreal'
  | 'cocos';

export type GameTemplateDimension = '2d' | '3d' | 'ui' | 'hybrid';

export type GameTemplateProfileTier = 'starter' | 'common' | 'advanced';

export interface GameTemplateProfile {
  id: string;
  labelZh: string;
  labelEn: string;
  dimension: GameTemplateDimension;
  tier: GameTemplateProfileTier;
  engines: readonly GameTemplateEngine[];
  tags: readonly string[];
  coreLoop: string;
  requiredGdd: readonly string[];
  coreSystems: readonly string[];
  assetSlots: readonly string[];
  codeHooks: readonly string[];
  browserAcceptance: readonly string[];
  engineAcceptance: readonly string[];
  limits: readonly string[];
}

export const GAME_TEMPLATE_PROFILES: readonly GameTemplateProfile[] = [
  {
    id: 'platformer',
    labelZh: '横版平台',
    labelEn: 'Platformer',
    dimension: '2d',
    tier: 'starter',
    engines: ['phaser', 'godot', 'unity', 'cocos', 'web'],
    tags: ['jump', 'physics', 'side-view'],
    coreLoop: '移动、跳跃、躲避、收集、到达终点。',
    requiredGdd: ['关卡节奏', '跳跃手感', '敌人与陷阱', '收集品', '胜负条件'],
    coreSystems: ['横向移动', '重力/跳跃', '平台碰撞', '检查点', '关卡完成'],
    assetSlots: ['player_sprite', 'tileset', 'enemy_sprite', 'pickup_icon', 'level_bg'],
    codeHooks: ['preloadAssets', 'createLevel', 'spawnPlayer', 'handleInput', 'checkGoal'],
    browserAcceptance: ['canvas 非空', '左右移动可见', '跳跃落地稳定', '可收集/到达终点'],
    engineAcceptance: ['碰撞层配置正确', '关卡场景可加载'],
    limits: ['复杂斜坡/绳索/高级移动先降级为基础跳跃'],
  },
  {
    id: 'top_down',
    labelZh: '俯视角动作 RPG',
    labelEn: 'Top-down Action RPG',
    dimension: '2d',
    tier: 'starter',
    engines: ['phaser', 'godot', 'unity', 'cocos', 'web'],
    tags: ['combat', 'inventory', 'top-down'],
    coreLoop: '探索地图、战斗、拾取、升级或推进任务。',
    requiredGdd: ['地图结构', '战斗规则', '角色成长', '物品', '任务目标'],
    coreSystems: ['八方向移动', '近战/远程攻击', '敌人 AI', '掉落', 'HUD'],
    assetSlots: ['hero_sprite', 'enemy_sprite', 'weapon_vfx', 'map_tileset', 'hud_icons'],
    codeHooks: ['createMap', 'spawnActor', 'resolveCombat', 'updateInventory', 'updateQuest'],
    browserAcceptance: ['角色可移动', '攻击命中有反馈', '敌人追踪/受击', 'HUD 更新'],
    engineAcceptance: ['导航/碰撞层可用', '动画状态机可切换'],
    limits: ['大型任务链和复杂背包先切 MVP 子集'],
  },
  {
    id: 'grid_logic',
    labelZh: '网格解谜',
    labelEn: 'Grid Puzzle',
    dimension: '2d',
    tier: 'starter',
    engines: ['phaser', 'godot', 'unity', 'cocos', 'web'],
    tags: ['grid', 'turn-based', 'logic'],
    coreLoop: '观察棋盘、移动/交换/推箱、触发规则、解出关卡。',
    requiredGdd: ['格子规则', '关卡目标', '障碍', '撤销/重开', '评分'],
    coreSystems: ['网格坐标', '规则解析', '步进回合', '撤销', '关卡切换'],
    assetSlots: ['tile_set', 'piece_icons', 'goal_icon', 'obstacle_icon', 'ui_buttons'],
    codeHooks: ['loadLevelData', 'applyMove', 'validateRule', 'checkSolved', 'undoMove'],
    browserAcceptance: ['棋盘显示', '输入改变格子状态', '非法操作被拒绝', '通关检测可见'],
    engineAcceptance: ['关卡数据可序列化', '网格坐标与渲染对齐'],
    limits: ['动态物理和实时战斗不放进此模板'],
  },
  {
    id: 'tower_defense',
    labelZh: '塔防',
    labelEn: 'Tower Defense',
    dimension: '2d',
    tier: 'starter',
    engines: ['phaser', 'godot', 'unity', 'cocos', 'web'],
    tags: ['waves', 'pathing', 'economy'],
    coreLoop: '布塔、开波、敌人沿路径前进、获得资源、升级防线。',
    requiredGdd: ['路径', '波次', '塔类型', '敌人类型', '经济规则'],
    coreSystems: ['路径跟随', '塔放置', '目标选择', '波次管理', '资源/生命'],
    assetSlots: ['tower_icons', 'enemy_sprite', 'projectile_vfx', 'path_tileset', 'hud_icons'],
    codeHooks: ['loadWavePlan', 'placeTower', 'spawnWave', 'selectTarget', 'resolveProjectile'],
    browserAcceptance: ['路径可见', '可放塔', '敌人移动', '塔攻击', '生命/金币变化'],
    engineAcceptance: ['寻路/路径点配置正确', '对象池无明显泄漏'],
    limits: ['自由建路和复杂寻路先限制为固定路径'],
  },
  {
    id: 'ui_heavy',
    labelZh: 'UI/视觉小说',
    labelEn: 'UI-heavy / Visual Novel',
    dimension: 'ui',
    tier: 'starter',
    engines: ['web', 'phaser', 'godot', 'unity', 'cocos'],
    tags: ['dialogue', 'choice', 'narrative'],
    coreLoop: '阅读剧情、做选择、触发状态变化、进入下一幕。',
    requiredGdd: ['剧本结构', '角色', '选择分支', '变量状态', 'UI 风格'],
    coreSystems: ['对话框', '选项', '剧情状态', '立绘/背景切换', '存读档'],
    assetSlots: ['character_portraits', 'backgrounds', 'choice_buttons', 'dialogue_ui', 'bgm'],
    codeHooks: ['loadScript', 'showLine', 'showChoices', 'applyChoice', 'saveState'],
    browserAcceptance: ['文本不溢出', '选项可点击', '背景/立绘切换', '状态影响后续'],
    engineAcceptance: ['字体/本地化资源可加载', '存档序列化稳定'],
    limits: ['复杂演出先拆成可脚本化镜头'],
  },
  {
    id: 'roguelike_dungeon',
    labelZh: 'Roguelike 地牢',
    labelEn: 'Roguelike Dungeon',
    dimension: 'hybrid',
    tier: 'common',
    engines: ['godot', 'unity', 'phaser', 'web', 'unreal'],
    tags: ['procedural', 'loot', 'permadeath'],
    coreLoop: '探索房间、战斗、拾取构筑、死亡重开。',
    requiredGdd: ['生成规则', '房间类型', '战斗节奏', '掉落池', '局外成长'],
    coreSystems: ['房间生成', '遭遇管理', '战利品', '状态效果', 'run 结算'],
    assetSlots: ['hero_sprite', 'monster_pack', 'room_tileset', 'loot_icons', 'skill_vfx'],
    codeHooks: ['generateDungeon', 'spawnEncounter', 'rollLoot', 'applyStatus', 'endRun'],
    browserAcceptance: ['房间生成可见', '门/传送生效', '战斗反馈', '死亡/通关重开'],
    engineAcceptance: ['随机种子可复现', '场景加载不丢引用'],
    limits: ['程序生成先用规则房间池，不做无限内容承诺'],
  },
  {
    id: 'metroidvania',
    labelZh: '类银河恶魔城',
    labelEn: 'Metroidvania',
    dimension: '2d',
    tier: 'advanced',
    engines: ['godot', 'unity', 'phaser', 'cocos'],
    tags: ['exploration', 'abilities', 'gating'],
    coreLoop: '探索连通地图、获得能力、解锁新区域、挑战 Boss。',
    requiredGdd: ['世界拓扑', '能力门', '移动能力', 'Boss', '回溯奖励'],
    coreSystems: ['平台移动', '能力解锁', '房间连接', '地图标记', 'Boss 状态机'],
    assetSlots: ['player_sheets', 'biome_tilesets', 'boss_sprite', 'ability_vfx', 'map_ui'],
    codeHooks: ['enterRoom', 'unlockAbility', 'gateByAbility', 'updateMap', 'startBoss'],
    browserAcceptance: ['房间切换', '能力改变可达性', '地图显示', 'Boss 受击/阶段'],
    engineAcceptance: ['场景流式加载可控', '碰撞层按能力区分'],
    limits: ['完整大地图先拆 MVP 区域'],
  },
  {
    id: 'bullet_hell_shmup',
    labelZh: '弹幕射击',
    labelEn: 'Bullet Hell / Shmup',
    dimension: '2d',
    tier: 'common',
    engines: ['phaser', 'godot', 'unity', 'cocos', 'web'],
    tags: ['projectiles', 'patterns', 'boss'],
    coreLoop: '躲避弹幕、射击敌人、清屏、挑战阶段。',
    requiredGdd: ['弹幕模式', '玩家判定', 'Boss 阶段', '火力成长', '得分'],
    coreSystems: ['对象池', '弹幕生成', '碰撞判定', 'Boss 阶段', '得分/炸弹'],
    assetSlots: ['ship_sprite', 'bullet_sprites', 'enemy_sprites', 'explosion_vfx', 'ui_icons'],
    codeHooks: ['spawnPattern', 'firePlayerWeapon', 'checkHitbox', 'advanceBossPhase', 'scoreKill'],
    browserAcceptance: ['大量弹体稳定', '玩家移动/射击', '命中/受击反馈', 'Boss 阶段切换'],
    engineAcceptance: ['对象池/批处理有效', '帧率无明显抖动'],
    limits: ['移动端先限弹量和特效数量'],
  },
  {
    id: 'twin_stick_shooter',
    labelZh: '双摇杆射击',
    labelEn: 'Twin-stick Shooter',
    dimension: 'hybrid',
    tier: 'common',
    engines: ['unity', 'godot', 'phaser', 'unreal', 'web'],
    tags: ['arena', 'aim', 'waves'],
    coreLoop: '移动、瞄准、射击、清波、升级武器。',
    requiredGdd: ['输入模型', '武器', '敌群', '竞技场', '升级选择'],
    coreSystems: ['移动/瞄准分离', '武器系统', '波次生成', '敌人寻路', '拾取升级'],
    assetSlots: ['player_sprite', 'weapon_vfx', 'enemy_pack', 'arena_bg', 'upgrade_icons'],
    codeHooks: ['readMoveAim', 'fireWeapon', 'spawnWave', 'resolvePickup', 'offerUpgrade'],
    browserAcceptance: ['WASD/触屏移动', '指针瞄准', '射击命中', '波次推进'],
    engineAcceptance: ['输入映射可切设备', '敌人数量性能可控'],
    limits: ['复杂网络合作不放入基础模板'],
  },
  {
    id: 'match3_casual_puzzle',
    labelZh: '三消/休闲消除',
    labelEn: 'Match-3 / Casual Puzzle',
    dimension: '2d',
    tier: 'starter',
    engines: ['web', 'phaser', 'cocos', 'unity', 'godot'],
    tags: ['match', 'casual', 'board'],
    coreLoop: '交换棋子、形成匹配、连锁下落、完成目标。',
    requiredGdd: ['棋盘尺寸', '匹配规则', '目标', '特殊棋子', '步数/时间'],
    coreSystems: ['棋盘填充', '交换验证', '匹配检测', '连锁结算', '关卡目标'],
    assetSlots: ['piece_icons', 'special_piece_icons', 'board_bg', 'vfx', 'level_ui'],
    codeHooks: ['fillBoard', 'trySwap', 'findMatches', 'resolveCascade', 'checkObjective'],
    browserAcceptance: ['棋子可交换', '匹配消除', '下落补齐', '目标/步数更新'],
    engineAcceptance: ['触控坐标准确', '动画队列不乱序'],
    limits: ['复杂活动系统先不做'],
  },
  {
    id: 'card_battler',
    labelZh: '卡牌战斗',
    labelEn: 'Card Battler',
    dimension: 'ui',
    tier: 'starter',
    engines: ['web', 'unity', 'godot', 'phaser', 'cocos'],
    tags: ['cards', 'deck', 'turn-based'],
    coreLoop: '抽牌、出牌、结算资源/效果、击败敌人或对手。',
    requiredGdd: ['卡牌类型', '资源系统', '回合结构', '敌人/对手', '牌库成长'],
    coreSystems: ['牌库/手牌', '费用', '目标选择', '效果解析', '回合结算'],
    assetSlots: ['card_frames', 'card_art', 'status_icons', 'enemy_art', 'battle_ui'],
    codeHooks: ['drawCards', 'playCard', 'resolveEffect', 'endTurn', 'updateDeck'],
    browserAcceptance: ['手牌显示', '可拖/点卡', '费用变化', '效果生效', '回合推进'],
    engineAcceptance: ['UI 事件命中准确', '卡牌数据可热更'],
    limits: ['复杂联机对战先降级为单机 AI'],
  },
  {
    id: 'auto_battler',
    labelZh: '自走棋/自动战斗',
    labelEn: 'Auto Battler',
    dimension: 'hybrid',
    tier: 'advanced',
    engines: ['unity', 'godot', 'unreal', 'web'],
    tags: ['synergy', 'placement', 'simulation'],
    coreLoop: '购买单位、摆放阵型、自动战斗、升级阵容。',
    requiredGdd: ['单位池', '羁绊', '商店', '战斗模拟', '经济'],
    coreSystems: ['商店刷新', '棋盘摆放', '羁绊计算', '自动战斗 AI', '回合结算'],
    assetSlots: ['unit_models', 'board_tiles', 'skill_vfx', 'synergy_icons', 'shop_ui'],
    codeHooks: ['rollShop', 'placeUnit', 'computeSynergy', 'simulateRound', 'settleRound'],
    browserAcceptance: ['商店可买', '单位可摆', '战斗自动进行', '胜负/金币变化'],
    engineAcceptance: ['单位寻路和技能目标稳定', '模拟可加速/暂停'],
    limits: ['多人匹配和复杂平衡先不做'],
  },
  {
    id: 'turn_based_tactics',
    labelZh: '回合战棋',
    labelEn: 'Turn-based Tactics',
    dimension: 'hybrid',
    tier: 'common',
    engines: ['unity', 'godot', 'unreal', 'web'],
    tags: ['grid', 'tactics', 'turns'],
    coreLoop: '选择单位、移动、攻击/技能、结束回合、达成战术目标。',
    requiredGdd: ['单位属性', '地形', '行动点', '技能', '胜负目标'],
    coreSystems: ['网格寻路', '行动顺序', '范围预览', '战斗公式', 'AI 回合'],
    assetSlots: ['unit_sprites_or_models', 'terrain_tiles', 'skill_vfx', 'range_ui', 'portrait_ui'],
    codeHooks: ['selectUnit', 'showReachable', 'executeAction', 'runAiTurn', 'checkBattleEnd'],
    browserAcceptance: ['格子选择', '移动范围显示', '行动结算', 'AI 回合推进'],
    engineAcceptance: ['寻路代价正确', '单位状态序列化稳定'],
    limits: ['高度差/视线先简化为格子代价'],
  },
  {
    id: 'rts',
    labelZh: '即时战略',
    labelEn: 'RTS',
    dimension: 'hybrid',
    tier: 'advanced',
    engines: ['unity', 'godot', 'unreal', 'web'],
    tags: ['selection', 'economy', 'units'],
    coreLoop: '采集资源、建造、训练单位、指挥战斗。',
    requiredGdd: ['资源', '建筑', '单位', '科技', '胜负条件'],
    coreSystems: ['框选/指令', '资源采集', '建造队列', '单位 AI', '迷雾/战斗'],
    assetSlots: ['unit_models', 'building_models', 'resource_nodes', 'command_ui', 'vfx'],
    codeHooks: ['selectUnits', 'issueCommand', 'gatherResource', 'buildStructure', 'resolveCombat'],
    browserAcceptance: ['框选/点选', '移动命令', '采集/建造', '敌我交战'],
    engineAcceptance: ['导航网格可用', '大批单位性能可控'],
    limits: ['完整 AI/多人先降级为脚本敌人'],
  },
  {
    id: 'city_builder_management',
    labelZh: '城市建造/经营',
    labelEn: 'City Builder / Management',
    dimension: 'hybrid',
    tier: 'common',
    engines: ['unity', 'godot', 'unreal', 'web'],
    tags: ['simulation', 'economy', 'placement'],
    coreLoop: '规划区域、建造设施、生产/消费资源、满足居民或目标。',
    requiredGdd: ['资源链', '建筑类型', '居民需求', '时间推进', '失败条件'],
    coreSystems: ['网格/地块放置', '生产链', '需求系统', '时间模拟', '报表 UI'],
    assetSlots: ['building_models', 'terrain_tiles', 'resource_icons', 'citizen_icons', 'panel_ui'],
    codeHooks: ['placeBuilding', 'tickEconomy', 'routeResource', 'updateDemand', 'showReport'],
    browserAcceptance: ['可放建筑', '资源数变化', '需求提示', '时间推进'],
    engineAcceptance: ['存档恢复一致', '长时间模拟无明显漂移'],
    limits: ['复杂交通先用抽象连通性'],
  },
  {
    id: 'farming_life_sim',
    labelZh: '农场/生活模拟',
    labelEn: 'Farming / Life Sim',
    dimension: 'hybrid',
    tier: 'common',
    engines: ['godot', 'unity', 'phaser', 'web'],
    tags: ['daily-cycle', 'farming', 'npc'],
    coreLoop: '日常行动、种植/制作、社交、升级家园。',
    requiredGdd: ['日夜季节', '作物', '工具', 'NPC', '制作/经济'],
    coreSystems: ['时间系统', '农田状态', '背包/工具', 'NPC 日程', '制作/商店'],
    assetSlots: ['character_sprites', 'crop_sprites', 'tool_icons', 'farm_tileset', 'npc_portraits'],
    codeHooks: ['advanceTime', 'useTool', 'growCrop', 'talkNpc', 'craftItem'],
    browserAcceptance: ['时间显示', '播种/浇水/收获', '背包变化', 'NPC 对话'],
    engineAcceptance: ['存档覆盖所有状态', 'TileMap 层级正确'],
    limits: ['完整开放镇子先拆单农场区域'],
  },
  {
    id: 'idle_clicker',
    labelZh: '放置/点击',
    labelEn: 'Idle / Clicker',
    dimension: 'ui',
    tier: 'starter',
    engines: ['web', 'phaser', 'cocos', 'unity', 'godot'],
    tags: ['incremental', 'economy', 'ui'],
    coreLoop: '点击获得资源、购买升级、自动产出、解锁新目标。',
    requiredGdd: ['资源曲线', '升级', '自动产出', '重置机制', 'UI 信息层级'],
    coreSystems: ['资源计数', '点击输入', '升级购买', '自动 tick', '离线收益'],
    assetSlots: ['button_art', 'resource_icons', 'upgrade_icons', 'panel_ui', 'feedback_vfx'],
    codeHooks: ['clickMain', 'buyUpgrade', 'tickIncome', 'saveProgress', 'computeOffline'],
    browserAcceptance: ['点击数值增长', '升级可买', '自动收益', '保存恢复'],
    engineAcceptance: ['本地存储/存档权限可用', '数值格式稳定'],
    limits: ['复杂商业化活动不进入基础模板'],
  },
  {
    id: 'rhythm_game',
    labelZh: '音乐节奏',
    labelEn: 'Rhythm Game',
    dimension: 'hybrid',
    tier: 'advanced',
    engines: ['unity', 'godot', 'phaser', 'web'],
    tags: ['audio-sync', 'timing', 'lanes'],
    coreLoop: '按音乐节拍输入、判定命中、连击、结算成绩。',
    requiredGdd: ['谱面格式', '判定窗口', '输入方式', '歌曲结构', '评分'],
    coreSystems: ['音频时钟', '谱面滚动', '输入判定', '连击/分数', '结果页'],
    assetSlots: ['note_sprites', 'lane_ui', 'hit_vfx', 'song_audio', 'result_ui'],
    codeHooks: ['loadChart', 'syncAudioClock', 'spawnNote', 'judgeInput', 'showResult'],
    browserAcceptance: ['音频播放', '音符滚动', '输入有判定', '分数/连击变化'],
    engineAcceptance: ['音频延迟可校准', '不同帧率判定稳定'],
    limits: ['在线排行和复杂编辑器后置'],
  },
  {
    id: 'racing',
    labelZh: '竞速',
    labelEn: 'Racing',
    dimension: '3d',
    tier: 'common',
    engines: ['unity', 'unreal', 'godot', 'web'],
    tags: ['vehicle', 'track', 'physics'],
    coreLoop: '驾驶、过弯、计圈、超越或刷新时间。',
    requiredGdd: ['车辆手感', '赛道', '计时/圈数', 'AI/目标', '相机'],
    coreSystems: ['车辆控制', '赛道检查点', '计时', '相机跟随', '碰撞/重置'],
    assetSlots: ['vehicle_model', 'track_mesh', 'environment_props', 'speed_ui', 'engine_sfx'],
    codeHooks: ['readVehicleInput', 'applyVehiclePhysics', 'passCheckpoint', 'resetCar', 'finishRace'],
    browserAcceptance: ['车辆可驾驶', '相机跟随', '检查点/圈数变化', '冲线结算'],
    engineAcceptance: ['物理材质稳定', 'WebGL/预览性能达标'],
    limits: ['高拟真悬挂先降级为街机手感'],
  },
  {
    id: 'fps',
    labelZh: '第一人称射击',
    labelEn: 'FPS',
    dimension: '3d',
    tier: 'advanced',
    engines: ['unreal', 'unity', 'godot', 'web'],
    tags: ['first-person', 'shooter', '3d'],
    coreLoop: '移动瞄准、射击、换弹、击败敌人、完成目标。',
    requiredGdd: ['武器', '敌人 AI', '关卡目标', '生命/护甲', '相机手感'],
    coreSystems: ['第一人称控制', '射线/弹道', '武器状态', '敌人 AI', 'HUD'],
    assetSlots: ['weapon_model', 'enemy_model', 'level_blockout', 'muzzle_vfx', 'hud_crosshair'],
    codeHooks: ['readLookMove', 'fireWeapon', 'reloadWeapon', 'damageTarget', 'completeObjective'],
    browserAcceptance: ['鼠标视角', '移动/跳跃', '射击命中', '敌人受击/死亡', 'HUD 更新'],
    engineAcceptance: ['输入锁定/释放正确', '碰撞体和导航可用'],
    limits: ['多人同步和高拟真枪械后置'],
  },
  {
    id: 'third_person_action',
    labelZh: '第三人称动作',
    labelEn: 'Third-person Action',
    dimension: '3d',
    tier: 'advanced',
    engines: ['unreal', 'unity', 'godot'],
    tags: ['character-controller', 'combat', 'camera'],
    coreLoop: '移动、锁定/攻击、闪避、击败敌人、推进场景。',
    requiredGdd: ['角色动作', '战斗节奏', '敌人', '相机', '关卡空间'],
    coreSystems: ['第三人称控制', '相机避障', '近战连段', '锁定', '敌人状态机'],
    assetSlots: ['hero_model', 'enemy_model', 'attack_animations', 'combat_vfx', 'arena_mesh'],
    codeHooks: ['readCharacterInput', 'updateCamera', 'startAttack', 'dodge', 'resolveLockOn'],
    browserAcceptance: ['角色移动', '相机跟随', '攻击/闪避反馈', '敌人受击'],
    engineAcceptance: ['动画蓝图/状态机可编译', '导航网格与碰撞匹配'],
    limits: ['复杂动作捕捉和连招树逐步加'],
  },
  {
    id: 'action_rpg_3d',
    labelZh: '3D 动作 RPG',
    labelEn: '3D Action RPG',
    dimension: '3d',
    tier: 'advanced',
    engines: ['unreal', 'unity', 'godot'],
    tags: ['rpg', 'quests', 'combat'],
    coreLoop: '探索区域、战斗、升级装备/技能、完成任务。',
    requiredGdd: ['成长系统', '装备/技能', '任务', '敌人', '区域结构'],
    coreSystems: ['角色控制', '战斗属性', '背包装备', '任务状态', '区域加载'],
    assetSlots: ['hero_model', 'equipment_models', 'enemy_models', 'quest_ui', 'skill_vfx'],
    codeHooks: ['equipItem', 'castSkill', 'gainXp', 'updateQuest', 'enterArea'],
    browserAcceptance: ['移动/战斗', '经验或装备变化', '任务 UI 更新', '区域目标完成'],
    engineAcceptance: ['资源引用稳定', '存档恢复角色状态'],
    limits: ['开放世界和复杂剧情线先缩到单区域'],
  },
  {
    id: 'survival_crafting',
    labelZh: '生存制作',
    labelEn: 'Survival Crafting',
    dimension: '3d',
    tier: 'advanced',
    engines: ['unity', 'unreal', 'godot', 'web'],
    tags: ['gathering', 'crafting', 'needs'],
    coreLoop: '采集资源、制作工具、管理需求、建造避难所。',
    requiredGdd: ['资源节点', '配方', '生存需求', '建造', '昼夜/危险'],
    coreSystems: ['采集', '背包', '配方制作', '建造放置', '饥渴/生命'],
    assetSlots: ['resource_models', 'tool_models', 'crafting_ui', 'building_parts', 'environment_mesh'],
    codeHooks: ['gatherResource', 'craftRecipe', 'placeBuildPart', 'tickNeeds', 'saveWorld'],
    browserAcceptance: ['采集资源', '制作物品', '放置建筑', '需求数值变化'],
    engineAcceptance: ['存档覆盖世界物件', '碰撞/放置规则一致'],
    limits: ['多人和体素破坏先不做'],
  },
  {
    id: 'open_world_exploration',
    labelZh: '开放探索',
    labelEn: 'Open-world Exploration',
    dimension: '3d',
    tier: 'advanced',
    engines: ['unreal', 'unity', 'godot'],
    tags: ['exploration', 'streaming', 'quests'],
    coreLoop: '探索地标、发现事件、收集资源、完成区域目标。',
    requiredGdd: ['世界分区', '地标', '移动方式', '发现奖励', '性能目标'],
    coreSystems: ['角色/载具移动', '区域流式', '发现点', '任务触发', '地图 UI'],
    assetSlots: ['terrain', 'landmark_meshes', 'foliage', 'map_ui', 'ambient_audio'],
    codeHooks: ['streamArea', 'discoverPoint', 'triggerEvent', 'updateMap', 'collectWorldItem'],
    browserAcceptance: ['可移动探索', '地标发现反馈', '地图/目标变化', '无空白首屏'],
    engineAcceptance: ['LOD/流式设置可用', '导出预览能打开'],
    limits: ['先做小型开放区域，不承诺无限世界'],
  },
  {
    id: 'platformer_3d',
    labelZh: '3D 平台跳跃',
    labelEn: '3D Platformer',
    dimension: '3d',
    tier: 'common',
    engines: ['unity', 'unreal', 'godot', 'web'],
    tags: ['jump', 'collectibles', 'camera'],
    coreLoop: '跑跳、相机控制、收集物、通过关卡挑战。',
    requiredGdd: ['移动手感', '相机关卡', '收集目标', '障碍', '终点'],
    coreSystems: ['三维角色控制', '跳跃/落地', '相机跟随', '收集品', '检查点'],
    assetSlots: ['character_model', 'platform_meshes', 'collectible_model', 'level_props', 'hud_icons'],
    codeHooks: ['moveCharacter', 'jump', 'collectItem', 'hitCheckpoint', 'reachGoal'],
    browserAcceptance: ['角色可移动/跳跃', '相机可控', '收集反馈', '掉落重置'],
    engineAcceptance: ['物理/碰撞稳定', '相机不穿模严重'],
    limits: ['复杂跑酷连招后置'],
  },
  {
    id: 'horror_escape_room',
    labelZh: '恐怖/密室逃脱',
    labelEn: 'Horror / Escape Room',
    dimension: '3d',
    tier: 'common',
    engines: ['unreal', 'unity', 'godot', 'web'],
    tags: ['puzzles', 'atmosphere', 'first-person'],
    coreLoop: '探索房间、找线索、解谜、躲避威胁、逃脱。',
    requiredGdd: ['空间布局', '谜题链', '线索', '威胁', '氛围音画'],
    coreSystems: ['第一人称交互', '物品/线索', '谜题状态', '门锁', '威胁触发'],
    assetSlots: ['room_mesh', 'prop_models', 'clue_ui', 'ambient_sfx', 'lighting_preset'],
    codeHooks: ['interactObject', 'pickupItem', 'solvePuzzle', 'unlockDoor', 'triggerScare'],
    browserAcceptance: ['可观察/交互物体', '拾取线索', '谜题改变状态', '门锁开关'],
    engineAcceptance: ['灯光/后处理可导出', '输入锁定和 UI 焦点稳定'],
    limits: ['高成本演出先用脚本事件'],
  },
  {
    id: 'fighting_game',
    labelZh: '格斗',
    labelEn: 'Fighting Game',
    dimension: 'hybrid',
    tier: 'advanced',
    engines: ['unity', 'godot', 'unreal', 'web'],
    tags: ['moves', 'hitboxes', 'versus'],
    coreLoop: '移动、出招、命中/防御、连招、击败对手。',
    requiredGdd: ['角色招式', '帧数据', '输入', '血量/能量', '胜负规则'],
    coreSystems: ['状态机', '输入缓冲', '碰撞盒/受击盒', '连击', '回合结算'],
    assetSlots: ['fighter_sheets_or_models', 'arena_bg', 'hit_vfx', 'ui_bars', 'announcer_sfx'],
    codeHooks: ['readMoveInput', 'enterState', 'spawnHitbox', 'resolveHit', 'endRound'],
    browserAcceptance: ['双方可操作或 AI', '出招命中', '血条变化', '回合胜负'],
    engineAcceptance: ['动画事件和碰撞帧对齐', '输入延迟可测'],
    limits: ['在线对战和完整平衡后置'],
  },
  {
    id: 'sports_arena',
    labelZh: '运动/竞技场',
    labelEn: 'Sports / Arena',
    dimension: '3d',
    tier: 'common',
    engines: ['unity', 'unreal', 'godot', 'web'],
    tags: ['ball', 'teams', 'score'],
    coreLoop: '控制角色/队伍、争夺目标物、得分、防守。',
    requiredGdd: ['运动规则', '控制方式', '计分', 'AI/队友', '场地'],
    coreSystems: ['角色移动', '球/目标物物理', '计分', '队伍 AI', '比赛计时'],
    assetSlots: ['player_models', 'arena_mesh', 'ball_model', 'scoreboard_ui', 'crowd_audio'],
    codeHooks: ['controlPlayer', 'kickOrThrow', 'updateScore', 'switchPossession', 'endMatch'],
    browserAcceptance: ['角色可控', '目标物可交互', '得分变化', '计时结束'],
    engineAcceptance: ['物理材质稳定', 'AI 导航可用'],
    limits: ['真实联赛规则和多人后置'],
  },
  {
    id: 'party_minigame_collection',
    labelZh: '派对小游戏合集',
    labelEn: 'Party / Minigame Collection',
    dimension: 'hybrid',
    tier: 'common',
    engines: ['unity', 'godot', 'phaser', 'web'],
    tags: ['minigames', 'rounds', 'local-multiplayer'],
    coreLoop: '选择小游戏、短局挑战、计分、轮换下一局。',
    requiredGdd: ['小游戏列表', '输入设备', '计分规则', '局间流程', '失败条件'],
    coreSystems: ['小游戏状态机', '本地玩家输入', '计分', '倒计时', '局间 UI'],
    assetSlots: ['avatar_sprites', 'minigame_ui', 'timer_ui', 'score_icons', 'sfx_pack'],
    codeHooks: ['startMinigame', 'routeInput', 'tickTimer', 'awardScore', 'showResults'],
    browserAcceptance: ['能进入小游戏', '输入响应', '倒计时/得分', '局间切换'],
    engineAcceptance: ['输入设备映射稳定', '场景切换释放资源'],
    limits: ['先做 2-3 个小游戏，不一次铺满合集'],
  },
  {
    id: 'space_flight_vehicle_sim',
    labelZh: '太空/飞行/载具模拟',
    labelEn: 'Space / Flight / Vehicle Sim',
    dimension: '3d',
    tier: 'advanced',
    engines: ['unity', 'unreal', 'godot', 'web'],
    tags: ['flight', 'vehicle', 'simulation'],
    coreLoop: '驾驶载具、导航、完成航线/战斗/采集目标。',
    requiredGdd: ['载具控制', '任务目标', '空间环境', '仪表 UI', '物理复杂度'],
    coreSystems: ['六自由度/飞行控制', '相机', '任务航点', '碰撞/伤害', '仪表盘'],
    assetSlots: ['vehicle_model', 'cockpit_ui', 'space_or_skybox', 'target_markers', 'engine_sfx'],
    codeHooks: ['readFlightInput', 'applyThrust', 'updateWaypoint', 'lockTarget', 'completeMission'],
    browserAcceptance: ['载具可飞/转向', '航点显示', '目标交互', '任务完成反馈'],
    engineAcceptance: ['物理时间步稳定', '大场景裁剪/LOD 可用'],
    limits: ['硬核物理先降级为街机飞行'],
  },
] as const;

export const STARTER_GAME_TEMPLATE_PROFILE_IDS = GAME_TEMPLATE_PROFILES.filter(
  (profile) => profile.tier === 'starter',
).map((profile) => profile.id);

export function gameTemplateProfileById(
  id: string,
): GameTemplateProfile | null {
  const normalized = id.trim().toLowerCase();
  return (
    GAME_TEMPLATE_PROFILES.find((profile) => profile.id === normalized) ?? null
  );
}

function labelForProfile(
  profile: GameTemplateProfile,
  locale: 'zh-CN' | 'en-US',
): string {
  return locale === 'zh-CN' ? profile.labelZh : profile.labelEn;
}

export function formatGameTemplateCatalogForPrompt(
  locale: 'zh-CN' | 'en-US' = 'zh-CN',
): string {
  const rows = GAME_TEMPLATE_PROFILES.map((profile, index) => {
    const label = labelForProfile(profile, locale);
    const engines = profile.engines.join('/');
    const systems = profile.coreSystems.slice(0, 3).join('、');
    return `${index + 1}. ${profile.id}：${label}｜${profile.dimension}｜${engines}｜${systems}`;
  }).join('\n');

  if (locale === 'en-US') {
    return `Template Profile registry (${GAME_TEMPLATE_PROFILES.length} mainstream templates):
${rows}

Integration rules:
- Select one primary template before drafting or freezing the GDD; infer conservatively when the user does not choose.
- Template Profile constrains GDD sections, asset_manifest slots, code hooks, and browser acceptance.
- Code skeletons may be partial; treat profiles as capability contracts first, then implement only supported hooks.
- Browser verification is mandatory for every template. Engine play/build/compile checks are supplemental.`;
  }

  return `游戏模板 Profile 注册表（${GAME_TEMPLATE_PROFILES.length} 个主流模板）：
${rows}

结合规则：
- GDD 起草或冻结前先选择一个 primary_template；用户未选时保守推断。
- Template Profile 约束 GDD 必填段、asset_manifest 槽位、代码 hook 和浏览器验收。
- 代码骨架可以分批补；Profile 先作为能力合同，落地时只实现已声明 hook。
- 每个模板都必须做浏览器验收；引擎 play/build/compile 只作补充。`;
}
